name: Gatsby Publish

on:
  workflow_dispatch:
  push:
    branches: staging
    paths-ignore: 
      - README.md
      - .github/workflows/*.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - name: Install claat tool
        run: go get github.com/mulesoft-consulting/codelabs-claat-tool/claat
      - run: yarn
      - run: yarn build
        env:
          GOOG_SA_EMAIL: ${{ secrets.GOOG_SA_EMAIL }}
          GOOG_SA_KEY: ${{ secrets.GOOG_SA_KEY }}
          GOOG_FOLDER_ID: ${{ secrets.GOOG_FOLDER_ID }}
          BUILD_ENV: prod
      - name: Upload site to staging dev
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET}}
          aws_bucket: stg-codelabs
          source_dir: public