name: Staging - Dev - Build Site

on:
  workflow_dispatch:
  push:
    branches: staging
    paths-ignore: 
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - name: Install claat tool
        run: go get github.com/mulesoft-consulting/codelabs-claat-tool/claat
      - run: yarn
      - run: yarn build
        env:
          GOOG_SA_EMAIL: ${{ secrets.GOOG_SA_EMAIL }}
          GOOG_SA_KEY: ${{ secrets.GOOG_SA_KEY }}
          GOOG_FOLDER_ID: ${{ secrets.GOOG_FOLDER_ID }}
          BUILD_ENV: dev
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTION_CATS: ${{ secrets.MONGO_COLLECTION_CATS }}
          MONGO_COLLECTION_LABS: ${{ secrets.MONGO_COLLECTION_LABS }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./public s3://stg-codelabs-dev